// Pure parser for a single Claude Code transcript (`~/.claude/projects/**/*.jsonl`).
// No filesystem access — it takes the file's text and returns one entry per user
// prompt, mirroring the Codex parser's contract.
//
// Claude does not record rate-limit percentages, so the limit windows come back
// empty; the report hides those columns for this agent.
//
// Two shapes matter here:
//  - a turn's cost is spread over every `assistant` line it produced (tool calls
//    and subagent/sidechain turns included), so they are summed into the prompt;
//  - one API response is written as several lines sharing the same `message.id`
//    (one per content block), so usage is counted once per id.
import type { PromptUsage } from '@shared/types/usage'
import { splitRoleCwd } from './usageCwd'

const EMPTY_LIMIT = { before: null, after: null, used: null }

/** Claude injects slash-command echoes, hook output and reminders as user turns. */
const INJECTED_BLOCK = /^<[a-zA-Z_][\w-]*>/
const INJECTED_CAVEAT = /^Caveat: The messages below were generated by the user/i
/** Synthetic turn Claude writes when the user stops a running response. */
const INTERRUPTION = /^\[Request interrupted/

function toNumber(value: unknown): number {
  return typeof value === 'number' && Number.isFinite(value) ? value : 0
}

function asRecord(value: unknown): Record<string, unknown> {
  return typeof value === 'object' && value !== null ? (value as Record<string, unknown>) : {}
}

/** Text of a real user prompt, or null for tool results and injected blocks. */
function readPrompt(event: Record<string, unknown>): string | null {
  if (event.isMeta === true || event.isSidechain === true || event.isCompactSummary === true) {
    return null
  }

  const content = asRecord(event.message).content
  let text = ''

  if (typeof content === 'string') {
    text = content
  } else if (Array.isArray(content)) {
    // A turn carrying any tool result is the harness answering the model, not
    // the user typing.
    if (content.some((part) => asRecord(part).type === 'tool_result')) return null
    text = content
      .filter((part) => asRecord(part).type === 'text')
      .map((part) => asRecord(part).text)
      .filter((value): value is string => typeof value === 'string')
      .join('\n')
  }

  text = text.trim()
  if (!text || INJECTED_BLOCK.test(text) || INJECTED_CAVEAT.test(text)) return null
  if (INTERRUPTION.test(text)) return null
  return text
}

/** Prompt being accumulated while its assistant turns stream in. */
interface PendingPrompt {
  prompt: string
  /** Conversation node the prompt hangs off — identifies a resend. */
  parentUuid: string | null
  timestamp: string
  endedAt: string
  model: string | null
  requests: number
  inputTokens: number
  cachedInputTokens: number
  outputTokens: number
  reasoningOutputTokens: number
}

export function parseClaudeSession(fileName: string, content: string): PromptUsage[] {
  const entries: PromptUsage[] = []
  const countedMessages = new Set<string>()
  let sessionId = fileName
  let cwd: string | null = null
  let branch: string | null = null
  let pending: PendingPrompt | null = null

  /**
   * A prompt that ran nothing and is followed by another prompt from the same
   * conversation point was superseded (the user resent or edited it) — it is
   * dropped instead of showing up as a duplicate costing nothing.
   */
  const supersededBy = (parentUuid: string | null): boolean =>
    pending !== null &&
    pending.requests === 0 &&
    parentUuid !== null &&
    pending.parentUuid === parentUuid

  const flush = (): void => {
    if (!pending) return
    const { projectCwd, terminalId } = splitRoleCwd(cwd)
    const totalTokens = pending.inputTokens + pending.outputTokens
    entries.push({
      id: `${fileName}#${entries.length}`,
      timestamp: pending.timestamp,
      sessionId,
      cwd,
      model: pending.model,
      effort: null,
      branch,
      prompt: pending.prompt,
      requests: pending.requests,
      endedAt: pending.endedAt,
      origin: terminalId ? 'iao' : 'external',
      terminalId,
      terminalTitle: null,
      projectCwd,
      inputTokens: pending.inputTokens,
      cachedInputTokens: pending.cachedInputTokens,
      outputTokens: pending.outputTokens,
      reasoningOutputTokens: pending.reasoningOutputTokens,
      totalTokens,
      fiveHour: { ...EMPTY_LIMIT },
      weekly: { ...EMPTY_LIMIT },
    })
    pending = null
  }

  for (const line of content.split('\n')) {
    if (!line.trim()) continue

    let event: Record<string, unknown>
    try {
      event = JSON.parse(line) as Record<string, unknown>
    } catch {
      continue
    }

    const timestamp = typeof event.timestamp === 'string' ? event.timestamp : ''
    if (typeof event.sessionId === 'string') sessionId = event.sessionId
    if (typeof event.cwd === 'string') cwd = event.cwd
    if (typeof event.gitBranch === 'string' && event.gitBranch) branch = event.gitBranch

    if (event.type === 'user') {
      const prompt = readPrompt(event)
      if (prompt === null) continue
      const parentUuid = typeof event.parentUuid === 'string' ? event.parentUuid : null
      if (supersededBy(parentUuid)) pending = null
      flush()
      pending = {
        prompt,
        parentUuid,
        timestamp,
        endedAt: timestamp,
        model: null,
        requests: 0,
        inputTokens: 0,
        cachedInputTokens: 0,
        outputTokens: 0,
        reasoningOutputTokens: 0,
      }
      continue
    }

    if (event.type !== 'assistant' || !pending) continue

    const message = asRecord(event.message)
    const usage = asRecord(message.usage)
    const id = typeof message.id === 'string' ? message.id : ''
    // One response spans several lines sharing an id — bill it once.
    if (!id || countedMessages.has(id)) continue
    countedMessages.add(id)

    const model = typeof message.model === 'string' ? message.model : null
    if (model && model !== '<synthetic>') pending.model = model

    const cacheRead = toNumber(usage.cache_read_input_tokens)
    pending.inputTokens +=
      toNumber(usage.input_tokens) + toNumber(usage.cache_creation_input_tokens) + cacheRead
    pending.cachedInputTokens += cacheRead
    pending.outputTokens += toNumber(usage.output_tokens)
    pending.reasoningOutputTokens += toNumber(asRecord(usage.output_tokens_details).thinking_tokens)
    pending.requests += 1
    if (timestamp) pending.endedAt = timestamp
  }

  flush()
  return entries
}
