import { describe, it, expect } from 'vitest'
import { parseClaudeSession } from './claudeUsage.parser'

const CWD = '/repos/app'

function line(event: unknown): string {
  return JSON.stringify(event)
}

function userPrompt(
  content: unknown,
  timestamp = '2026-08-28T12:00:00.000Z',
  extra: Record<string, unknown> = {},
): string {
  return line({
    type: 'user',
    timestamp,
    sessionId: 'sess-1',
    cwd: CWD,
    gitBranch: 'main',
    message: { role: 'user', content },
    ...extra,
  })
}

function assistant(
  id: string,
  usage: Record<string, unknown>,
  timestamp = '2026-08-28T12:00:10.000Z',
  extra: Record<string, unknown> = {},
): string {
  return line({
    type: 'assistant',
    timestamp,
    sessionId: 'sess-1',
    cwd: CWD,
    message: { id, model: 'claude-opus-5', usage },
    ...extra,
  })
}

describe('parseClaudeSession', () => {
  it('emite uma entrada por prompt com tokens, modelo e branch', () => {
    const content = [
      userPrompt('ajusta o layout'),
      assistant('msg-1', {
        input_tokens: 4,
        cache_creation_input_tokens: 35_000,
        cache_read_input_tokens: 1_000,
        output_tokens: 250,
        output_tokens_details: { thinking_tokens: 40 },
      }),
    ].join('\n')

    const [entry, ...rest] = parseClaudeSession('/logs/a.jsonl', content)

    expect(rest).toEqual([])
    expect(entry).toMatchObject({
      sessionId: 'sess-1',
      cwd: CWD,
      model: 'claude-opus-5',
      branch: 'main',
      effort: null,
      prompt: 'ajusta o layout',
      requests: 1,
      inputTokens: 36_004,
      cachedInputTokens: 1_000,
      outputTokens: 250,
      reasoningOutputTokens: 40,
      totalTokens: 36_254,
    })
    expect(entry.fiveHour).toEqual({ before: null, after: null, used: null })
    expect(entry.weekly).toEqual({ before: null, after: null, used: null })
  })

  it('conta uma única vez as linhas que repetem o mesmo message.id', () => {
    const usage = { input_tokens: 10, output_tokens: 5 }
    const content = [
      userPrompt('roda os testes'),
      assistant('msg-1', usage),
      assistant('msg-1', usage),
      assistant('msg-2', usage),
    ].join('\n')

    expect(parseClaudeSession('/logs/a.jsonl', content)[0]).toMatchObject({
      requests: 2,
      inputTokens: 20,
      outputTokens: 10,
      totalTokens: 30,
    })
  })

  it('soma as chamadas de ferramenta e os subagentes ao prompt que os disparou', () => {
    const content = [
      userPrompt('investiga o bug'),
      assistant('msg-1', { input_tokens: 100, output_tokens: 10 }),
      // resultado de ferramenta: não é um prompt novo
      userPrompt([{ type: 'tool_result', tool_use_id: 'toolu_1', content: 'ok' }]),
      assistant('msg-2', { input_tokens: 200, output_tokens: 20 }),
      // turno de subagente (sidechain) — o custo é do mesmo prompt
      assistant('msg-3', { input_tokens: 50, output_tokens: 5 }, '2026-08-28T12:01:00.000Z', {
        isSidechain: true,
      }),
    ].join('\n')

    const entries = parseClaudeSession('/logs/a.jsonl', content)

    expect(entries).toHaveLength(1)
    expect(entries[0]).toMatchObject({
      requests: 3,
      inputTokens: 350,
      outputTokens: 35,
      endedAt: '2026-08-28T12:01:00.000Z',
    })
  })

  it('ignora eco de slash command, saída de hook e system-reminder', () => {
    const content = [
      userPrompt('<command-name>/clear</command-name>'),
      userPrompt('<local-command-stdout>ok</local-command-stdout>'),
      userPrompt('Caveat: The messages below were generated by the user while running local commands.'),
      userPrompt('prompt de verdade'),
      assistant('msg-1', { input_tokens: 10, output_tokens: 1 }),
    ].join('\n')

    const entries = parseClaudeSession('/logs/a.jsonl', content)

    expect(entries).toHaveLength(1)
    expect(entries[0].prompt).toBe('prompt de verdade')
  })

  it('ignora mensagens meta, de subagente e resumos de compactação', () => {
    const content = [
      userPrompt('do subagente', '2026-08-28T12:00:00.000Z', { isSidechain: true }),
      userPrompt('meta', '2026-08-28T12:00:01.000Z', { isMeta: true }),
      userPrompt('resumo', '2026-08-28T12:00:02.000Z', { isCompactSummary: true }),
    ].join('\n')

    expect(parseClaudeSession('/logs/a.jsonl', content)).toEqual([])
  })

  it('aceita prompt em blocos de texto e ignora linhas inválidas', () => {
    const content = [
      'not json',
      '',
      userPrompt([
        { type: 'text', text: 'primeira parte' },
        { type: 'text', text: 'segunda parte' },
      ]),
    ].join('\n')

    const entries = parseClaudeSession('/logs/a.jsonl', content)

    expect(entries).toHaveLength(1)
    expect(entries[0].prompt).toBe('primeira parte\nsegunda parte')
    expect(entries[0].totalTokens).toBe(0)
  })

  it('identifica o terminal do IAO pelo diretório de role', () => {
    const content = line({
      type: 'user',
      timestamp: '2026-08-28T12:00:00.000Z',
      sessionId: 'sess-1',
      cwd: '/repos/app/.iao/roles/term-7',
      message: { role: 'user', content: 'oi' },
    })

    expect(parseClaudeSession('/logs/a.jsonl', content)[0]).toMatchObject({
      origin: 'iao',
      terminalId: 'term-7',
      projectCwd: '/repos/app',
    })
  })

  it('retorna vazio para um arquivo sem prompts', () => {
    expect(parseClaudeSession('/logs/a.jsonl', '')).toEqual([])
  })

  it('ignora o marcador de interrupção do usuário', () => {
    const content = [
      userPrompt('[Request interrupted by user]'),
      userPrompt('continua daqui'),
      assistant('msg-1', { input_tokens: 10, output_tokens: 1 }),
    ].join('\n')

    const entries = parseClaudeSession('/logs/a.jsonl', content)

    expect(entries).toHaveLength(1)
    expect(entries[0].prompt).toBe('continua daqui')
  })

  it('descarta o prompt reenviado que não chegou a rodar nada', () => {
    const content = [
      userPrompt('mesma pergunta', '2026-08-28T12:00:00.000Z', { parentUuid: 'node-1' }),
      userPrompt('mesma pergunta', '2026-08-28T12:01:00.000Z', { parentUuid: 'node-1' }),
      assistant('msg-1', { input_tokens: 100, output_tokens: 10 }),
    ].join('\n')

    const entries = parseClaudeSession('/logs/a.jsonl', content)

    expect(entries).toHaveLength(1)
    expect(entries[0]).toMatchObject({
      timestamp: '2026-08-28T12:01:00.000Z',
      requests: 1,
      totalTokens: 110,
    })
  })

  it('mantém prompts distintos que não rodaram nada (interrompidos)', () => {
    const content = [
      userPrompt('primeiro', '2026-08-28T12:00:00.000Z', { parentUuid: 'node-1' }),
      userPrompt('segundo', '2026-08-28T12:01:00.000Z', { parentUuid: 'node-2' }),
    ].join('\n')

    expect(parseClaudeSession('/logs/a.jsonl', content).map((e) => e.prompt)).toEqual([
      'primeiro',
      'segundo',
    ])
  })
})
