// Delivers a terminal's prompt to its agent the way Maestri does: by launching
// the agent in a per-terminal subdirectory that carries its own native context
// file (CLAUDE.md / AGENTS.md / …). The agent reads the role from that file as
// part of its normal startup context — agents resolve context files by walking
// up from the cwd, so it still sees (and merges) the repository's own root
// CLAUDE.md/AGENTS.md, which IAO never touches.
//
// The subdirectory lives under `<repo>/.iao/roles/<roleId>/`, is fully owned by
// IAO, and the `.iao/` tree is added to the repo's `.gitignore` once so it never
// dirties version control. Each terminal gets its own `roleId`, so two terminals
// in the same folder — even running the same agent — carry distinct prompts.
//
// Best-effort: a failure here (unwritable cwd, …) must not block the pty. On any
// failure the function returns null and the caller launches the agent in the
// repo root with no role.
import { existsSync, mkdirSync, readFileSync, writeFileSync, appendFileSync, rmSync } from 'fs'
import { dirname, join } from 'path'

// Project-relative root under which every terminal gets its own role directory.
// The whole tree is IAO-managed and gitignored.
export const ROLE_ROOT = join('.iao', 'roles')

// Markdown comment placed atop every generated role file, so a human who opens
// it understands it is machine-managed. Invisible to the agent's reading.
const HEADER =
  '<!-- Generated by Infinity Agent Orchestrator — edit the terminal prompt, not this file. -->'

/**
 * Trailing section appended to every generated role file. The agent is launched
 * in the isolated role directory, so its native context file is this one; this
 * footer forces it to ALSO load the repository's own root context file so it
 * never works from the terminal-specific role alone, blind to the project. The
 * `contextFile` (e.g. `CLAUDE.md` / `AGENTS.md`) is named explicitly so the
 * instruction points at the file the agent actually reads.
 */
function roleFooter(contextFile: string): string {
  return [
    '---',
    '',
    '## Project context — required',
    '',
    `This file lives in an isolated IAO role directory (\`.iao/roles/<id>/\`), not at`,
    `the project root. Before doing anything, you MUST also read and follow the`,
    `project's own \`${contextFile}\` at the repository root. That root \`${contextFile}\``,
    `is the authoritative source of project context, conventions, and constraints;`,
    `the instructions above are only your additional, terminal-specific role. Do not`,
    `rely on this role file alone — always load the project's root \`${contextFile}\``,
    `first and combine it with the role above.`,
  ].join('\n')
}

/** Absolute path of a terminal's private role directory inside the project. */
function roleDir(repoCwd: string, roleId: string): string {
  return join(repoCwd, ROLE_ROOT, roleId)
}

/**
 * Add `.iao/` to `<repoCwd>/.gitignore` so IAO's role tree never dirties version
 * control. Only acts inside a git repo (a `.git` entry exists), is a no-op when
 * the directory is already ignored, and creates `.gitignore` if absent.
 */
function ignoreInGit(repoCwd: string): void {
  if (!existsSync(join(repoCwd, '.git'))) return
  const gitignore = join(repoCwd, '.gitignore')
  const current = existsSync(gitignore) ? readFileSync(gitignore, 'utf8') : ''
  // Treat `.iao`, `.iao/`, `/.iao` and `/.iao/` as the same entry.
  const normalize = (line: string): string => line.trim().replace(/^\//, '').replace(/\/$/, '')
  if (current.split('\n').some((line) => normalize(line) === '.iao')) return
  const prefix = current && !current.endsWith('\n') ? '\n' : ''
  appendFileSync(gitignore, `${prefix}.iao/\n`)
}

/**
 * Materialize `prompt` as the agent's context file inside this terminal's own
 * role directory, and return that directory for the caller to use as the agent's
 * cwd. The repository's own files are never written. An empty prompt removes any
 * previous role file and returns null, so the agent launches in the repo root.
 *
 * Returns null on any failure too — the pty must still launch (in the repo root).
 */
export function applyPrompt(
  repoCwd: string,
  roleId: string,
  contextFile: string,
  prompt: string,
): string | null {
  try {
    const dir = roleDir(repoCwd, roleId)
    const target = join(dir, contextFile)
    const trimmed = prompt.trim()

    // No prompt → no role: drop any stale file and let the agent run in the repo.
    if (!trimmed) {
      if (existsSync(target)) rmSync(target)
      return null
    }

    // The role file is 100% IAO-owned, so it is written wholesale — no markers,
    // no user content to preserve. `dirname` covers nested context files such as
    // `.github/copilot-instructions.md`.
    mkdirSync(dirname(target), { recursive: true })
    writeFileSync(target, `${HEADER}\n\n${trimmed}\n\n${roleFooter(contextFile)}\n`, 'utf8')
    ignoreInGit(repoCwd)
    return dir
  } catch (err) {
    console.warn('[promptFile] applyPrompt skipped:', (err as Error).message)
    return null
  }
}
